using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using System;

public class PlacementRegister : MonoBehaviour {

    public Dictionary<string, int> integerCoordinates;

    void Awake()
    {
        // Creates dictionary to register GameObject placements in playspace. 
        // Key is string of integer coordinates generated by CubeFinder.
        // Value is integer representing object's unique GameID (see Unity Object.GetInstanceID). 
        integerCoordinates = new Dictionary<string, int>();
    }

    public string CoordinatesVector3ToString(Vector3 vector3Coordinates)
    {
        // Converts Vector3 coordinates to string of format "+xxx +yyy +zzz".
        // This string is used as key in integerCoordinates dictionary. 
        string stringCoordinates = "";
        for (int i = 0; i < 3; i++)
        {
            float floatCoordinate = vector3Coordinates[i];
            int coordinate = Mathf.RoundToInt(floatCoordinate);
            if (coordinate >= 0)
            {
                stringCoordinates += "+" + coordinate.ToString("D3");
            }
            else
            {
                stringCoordinates += coordinate.ToString("D3");
            }
            if (i < 2)
            {
                stringCoordinates += " ";
            }
        }
        return stringCoordinates;
    }

    public Vector3 CoordinatesStringToVector3(string stringCoordinates)
    {
        // Takes coordinate string and converts it to Vector3.
        int xCoordinate = Int32.Parse(stringCoordinates.Substring(0, 4));
        int yCoordinate = Int32.Parse(stringCoordinates.Substring(5, 4));
        int zCoordinate = Int32.Parse(stringCoordinates.Substring(10, 4));

        Vector3 vector3Coordinates = new Vector3(xCoordinate, yCoordinate, zCoordinate);

        return vector3Coordinates;
    }
}
